[package]
authors = ["Ishan Dutta <ishandutta2007@gmail.com>"]

name = "sublime-rust-gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = "=0.2.2"
gpui-component = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
